package com.teamgannon.trips.service;

import com.teamgannon.trips.jpa.model.ExoPlanet;
import com.teamgannon.trips.jpa.model.SolarSystem;
import com.teamgannon.trips.jpa.model.SolarSystemFeature;
import com.teamgannon.trips.jpa.model.StarObject;
import com.teamgannon.trips.jpa.repository.ExoPlanetRepository;
import com.teamgannon.trips.jpa.repository.SolarSystemFeatureRepository;
import com.teamgannon.trips.jpa.repository.SolarSystemRepository;
import com.teamgannon.trips.solarsystem.modelling.accrete.Planet;
import com.teamgannon.trips.solarsystem.modelling.accrete.PostAccretionGenerator;
import com.teamgannon.trips.solarsystem.modelling.accrete.StarSystem;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.function.Function;

/**
 * Persists planets, moons, and belt features generated by the ACCRETE
 * pipeline into the TRIPS data model.
 * <p>
 * Extracted from {@code SolarSystemService} in Phase 4.7 of the
 * codebase-review remediation. The persistence boundary is split out so
 * {@code SolarSystemService} can stay focused on system retrieval / lookup
 * and the procedural-generation save path lives on its own.
 *
 * <h2>Workflow</h2>
 * <ol>
 *   <li>{@link #savePlanets} — converts ACCRETE {@link Planet}s into
 *       {@link ExoPlanet}s + moons, deletes prior "Simulated" rows for the
 *       system, updates the SolarSystem's planet count + habitable-zone flag.</li>
 *   <li>{@link #saveBelts} — promotes the {@link PostAccretionGenerator}
 *       asteroid + Kuiper belts into {@link SolarSystemFeature} rows.</li>
 *   <li>{@link #saveSystem} — convenience that runs both.</li>
 * </ol>
 *
 * <h2>Cross-service dependency</h2>
 * Both save methods need a "find or create the system row for this star".
 * Rather than dragging that logic over (it touches several other
 * SolarSystemService internals), the caller passes a
 * {@link Function}&lt;StarObject, SolarSystem&gt; — typically
 * {@code solarSystemService::findOrCreateSolarSystem}.
 */
@Slf4j
@Component
public class GeneratedSystemPersister {

    private final SolarSystemRepository solarSystemRepository;
    private final ExoPlanetRepository exoPlanetRepository;
    private final SolarSystemFeatureRepository featureRepository;
    private final ExoPlanetCrudService exoPlanetCrudService;

    public GeneratedSystemPersister(SolarSystemRepository solarSystemRepository,
                                    ExoPlanetRepository exoPlanetRepository,
                                    SolarSystemFeatureRepository featureRepository,
                                    ExoPlanetCrudService exoPlanetCrudService) {
        this.solarSystemRepository = solarSystemRepository;
        this.exoPlanetRepository = exoPlanetRepository;
        this.featureRepository = featureRepository;
        this.exoPlanetCrudService = exoPlanetCrudService;
    }

    /**
     * Save generated planets + their moons. Returns the total number of bodies
     * saved (planets + moons). Existing "Simulated" rows for this system are
     * deleted first.
     */
    @Transactional
    public int savePlanets(StarObject sourceStar,
                           List<Planet> planets,
                           Function<StarObject, SolarSystem> solarSystemLookup) {
        if (sourceStar == null || planets == null || planets.isEmpty()) {
            log.warn("Cannot save generated planets: source star or planets list is null/empty");
            return 0;
        }

        SolarSystem solarSystem = solarSystemLookup.apply(sourceStar);

        // Remove prior simulated planets so we don't double up.
        List<ExoPlanet> existingPlanets = exoPlanetRepository.findBySolarSystemId(solarSystem.getId());
        for (ExoPlanet existing : existingPlanets) {
            if ("Simulated".equals(existing.getDetectionType())) {
                exoPlanetRepository.delete(existing);
            }
        }

        int savedCount = 0;
        int moonCount = 0;
        int planetIndex = 1;

        for (Planet planet : planets) {
            ExoPlanet exoPlanet = AccretePlanetConverter.convert(
                    planet, sourceStar, solarSystem.getId(), planetIndex++, null, false);
            exoPlanetRepository.save(exoPlanet);
            savedCount++;

            log.debug("Saved generated planet: {} (SMA={} AU, Mass={} Earth masses)",
                    exoPlanet.getName(), exoPlanet.getSemiMajorAxis(), exoPlanet.getMass());

            List<Planet> moons = planet.getMoons();
            if (moons != null && !moons.isEmpty()) {
                int moonIndex = 1;
                for (Planet moon : moons) {
                    ExoPlanet exoMoon = AccretePlanetConverter.convert(
                            moon, sourceStar, solarSystem.getId(), moonIndex++, exoPlanet.getId(), true);
                    exoMoon.setName(exoPlanet.getName() + " " + AccretePlanetConverter.toRomanNumeral(moonIndex - 1));
                    exoPlanetRepository.save(exoMoon);
                    moonCount++;
                    log.debug("Saved generated moon: {} (parent: {}, SMA={} AU)",
                            exoMoon.getName(), exoPlanet.getName(), exoMoon.getSemiMajorAxis());
                }
            }
        }

        solarSystem.setPlanetCount(savedCount);
        exoPlanetCrudService.updateHabitableZonePlanetStatus(solarSystem);
        solarSystemRepository.save(solarSystem);

        log.info("Saved {} generated planets and {} moons for star '{}' (system ID: {})",
                savedCount, moonCount, sourceStar.getDisplayName(), solarSystem.getId());

        return savedCount + moonCount;
    }

    /**
     * Save asteroid + Kuiper belt features from a generated {@link StarSystem}.
     * Existing simulated belt rows (notes contain "Generated by ACCRETE") are
     * removed first.
     */
    @Transactional
    public void saveBelts(StarObject sourceStar,
                          StarSystem starSystem,
                          Function<StarObject, SolarSystem> solarSystemLookup) {
        SolarSystem solarSystem = solarSystemLookup.apply(sourceStar);
        String solarSystemId = solarSystem.getId();

        // Wipe prior simulated belts.
        List<SolarSystemFeature> existingFeatures = featureRepository.findBySolarSystemId(solarSystemId);
        for (SolarSystemFeature feature : existingFeatures) {
            if (feature.getNotes() != null && feature.getNotes().contains("Generated by ACCRETE")) {
                featureRepository.delete(feature);
            }
        }

        PostAccretionGenerator.AsteroidBeltData asteroidBelt = starSystem.getAsteroidBelt();
        if (asteroidBelt != null) {
            featureRepository.save(buildAsteroidBelt(asteroidBelt, solarSystemId));
            log.info("Saved generated asteroid belt: {} - {} AU",
                    "%.2f".formatted(asteroidBelt.getInnerRadiusAU()),
                    "%.2f".formatted(asteroidBelt.getOuterRadiusAU()));
        }

        PostAccretionGenerator.KuiperBeltData kuiperBelt = starSystem.getKuiperBelt();
        if (kuiperBelt != null) {
            featureRepository.save(buildKuiperBelt(kuiperBelt, solarSystemId));
            log.info("Saved generated Kuiper belt: {} - {} AU",
                    "%.2f".formatted(kuiperBelt.getInnerRadiusAU()),
                    "%.2f".formatted(kuiperBelt.getOuterRadiusAU()));
        }
    }

    /** Convenience: save planets, then belts, in one call. Returns planet/moon body count. */
    @Transactional
    public int saveSystem(StarObject sourceStar,
                          StarSystem starSystem,
                          Function<StarObject, SolarSystem> solarSystemLookup) {
        if (starSystem == null) {
            log.warn("Cannot save: starSystem is null");
            return 0;
        }
        int savedCount = savePlanets(sourceStar, starSystem.getPlanets(), solarSystemLookup);
        saveBelts(sourceStar, starSystem, solarSystemLookup);
        return savedCount;
    }

    private static SolarSystemFeature buildAsteroidBelt(PostAccretionGenerator.AsteroidBeltData belt,
                                                         String solarSystemId) {
        SolarSystemFeature f = new SolarSystemFeature(
                belt.getName(),
                SolarSystemFeature.FeatureType.ASTEROID_BELT,
                SolarSystemFeature.FeatureCategory.NATURAL);
        f.setSolarSystemId(solarSystemId);
        f.setInnerRadiusAU(belt.getInnerRadiusAU());
        f.setOuterRadiusAU(belt.getOuterRadiusAU());
        f.setInclinationDeg(belt.getInclinationDeg());
        f.setEccentricity(belt.getEccentricity());
        f.setThickness(0.15);
        f.setParticleCount(5000);
        f.setMinParticleSize(0.5);
        f.setMaxParticleSize(2.0);
        f.setPrimaryColor("#8C8278");
        f.setSecondaryColor("#645A50");
        f.setOpacity(0.8);
        f.setAnimated(true);
        f.setAnimationSpeed(1.0);
        f.setNotes(String.format("Generated by ACCRETE. Estimated mass: %.4f Earth masses",
                belt.getMassEarthMasses()));
        return f;
    }

    private static SolarSystemFeature buildKuiperBelt(PostAccretionGenerator.KuiperBeltData belt,
                                                       String solarSystemId) {
        SolarSystemFeature f = new SolarSystemFeature(
                belt.getName(),
                SolarSystemFeature.FeatureType.KUIPER_BELT,
                SolarSystemFeature.FeatureCategory.NATURAL);
        f.setSolarSystemId(solarSystemId);
        f.setInnerRadiusAU(belt.getInnerRadiusAU());
        f.setOuterRadiusAU(belt.getOuterRadiusAU());
        f.setInclinationDeg(belt.getInclinationDeg());
        f.setEccentricity(belt.getEccentricity());
        f.setThickness(0.2);
        f.setParticleCount(3000);
        f.setMinParticleSize(0.8);
        f.setMaxParticleSize(3.0);
        f.setPrimaryColor("#B4BEC8");
        f.setSecondaryColor("#8C8C96");
        f.setOpacity(0.6);
        f.setAnimated(true);
        f.setAnimationSpeed(0.5);
        f.setNotes(String.format("Generated by ACCRETE. Estimated mass: %.4f Earth masses",
                belt.getMassEarthMasses()));
        return f;
    }
}
