package com.teamgannon.trips.astrogation.util;

public class Units {

    /**
     * Converts Right Ascension (RA) given in hours, minutes, and seconds to degrees
     *
     * @param hours   The hours to convert
     * @param minutes The minutes to convert
     * @param seconds The seconds to convert
     * @return The converted value
     */
    public static double convertToDegrees(double hours, double minutes, double seconds) {
        return convertToUnit(hours, minutes, seconds, 360); // Multiply by 360 to get degrees
    }

    /**
     * Converts Right Ascension (RA) given in radians to degrees
     *
     * @param degrees The degrees to convert
     * @return The converted value
     */
    public static double convertDegreesToRadians(double degrees) {
        return degrees * Math.PI / 180;
    }


    /**
     * Converts Right Ascension (RA) given in radians to degrees
     *
     * @param radians The radians to convert
     * @return The converted value
     */
    public static double convertRadiansToDegrees(double radians) {
        return radians * 180 / Math.PI;
    }

    /**
     * Converts Right Ascension (RA) given in hours, minutes, and seconds to radians
     *
     * @param hours   The hours to convert
     * @param minutes The minutes to convert
     * @param seconds The seconds to convert
     * @return The converted value
     */
    public static double convertToRadians(double hours, double minutes, double seconds) {
        return convertToUnit(hours, minutes, seconds, 2 * Math.PI); // Multiply by 2 * PI to get radians
    }

    /**
     * General conversion function for RA to either degrees or radians
     * Takes the hours, minutes, seconds, and a multiplication factor to determine the unit
     *
     * @param hours   The hours to convert
     * @param minutes The minutes to convert
     * @param seconds The seconds to convert
     * @param factor  The factor to multiply by to convert to the desired unit
     * @return The converted value
     */
    private static double convertToUnit(double hours, double minutes, double seconds, double factor) {
        // Convert hours, minutes, and seconds to a fraction of a day
        double fractionOfDay = (hours + minutes / 60.0 + seconds / 3600.0) / 24.0;

        // Multiply the fraction of a day by the given factor to convert to the desired unit
        return fractionOfDay * factor;
    }

    /**
     * Converts degrees to Right Ascension (RA) in hours, minutes, and seconds
     *
     * @param degrees The degrees to convert
     * @return An instance of HoursMinutesSeconds containing the converted RA
     */
    public static HoursMinutesSeconds convertToHoursMinutesSeconds(double degrees) {
        // Convert degrees to a fraction of a 24-hour day
        double fractionOfDay = degrees / 360.0 * 24.0;

        // Extract the integer part of the hours, and leave the fractional part
        double hours = Math.floor(fractionOfDay);

        // Convert the fractional part of the hours to minutes
        double fractionOfHour = (fractionOfDay - hours) * 60.0;
        double minutes = Math.floor(fractionOfHour);

        // Convert the remaining fractional part to seconds
        double seconds = (fractionOfHour - minutes) * 60.0;

        // Use the all-args constructor generated by Lombok to create an instance
        return new HoursMinutesSeconds(hours, minutes, seconds);
    }

}
